### ISSUE TITLE
make it compatible with ftrobopy/fttxpy/ftifpy

### ISSUE THREAD

**Issue by ski7777** [Bloeckchengrafik/ftswarm.py#4]

**Comment by Bloeckchengrafik** [comment]
this may be a dumb question, but what is not compatible about this?

**Comment by ski7777** [comment]
As far as I can see the whole API of this lib seems to have at least a
different naming scheme for the peripherals and their functionality. Just
adding some aliases should solve the problem.

Christian Bergschneider ***@***.***> schrieb am Sa., 6. Jan.
2024, 00:46:

**Comment by Bloeckchengrafik** [comment]
In this API, I try to improve the following parts over the ftrobopy api:

1. **Synchronous Behavior:**
   The current synchronous behavior in the ftrobopy API poses a challenge, particularly considering the slower nature of communication with external hardware. The time spent waiting for IO could be better utilized by other parts of the program, especially given the text-based protocol. Addressing this could significantly enhance the overall efficiency of programs interacting with external hardware.

2. **Naming Convention:**
   The ftrobopy-style mixedCase naming convention diverges from the Python PEP 8 Style Guide, which I prefer to adhere to in all my Python software projects. For reference, you can review the PEP 8 guidelines on function and variable names [here](https://peps.python.org/pep-0008/#function-and-variable-names). Aligning with these conventions contributes to better code readability and maintainability.

3. **Lack of Typehints Support:**
   Another notable aspect is the absence of support for Python type hints in the ftrobopy API. With everything structured as one large class with subclasses, incorporating type hints could enhance code clarity and facilitate better collaboration among developers.


Another part is the naming of things: (Why is there a digital input and a switch?)
In my development practices, I strive to align function and class naming with the official ftSwarm [C++ API](https://elektrofuzzis.github.io/de/cpp-api/index). This ensures a smoother transition when building swarm applications in both Python and C++.

It's worth mentioning that the last part of my feedback explains why I name my components the way I do, and it's not a critique of the ftrobopy API itself. While a synchronous wrapper API with ftrobopy-style naming could be a workaround, maintaining it may not be feasible due to time constraints.

I apologize for the length of this feedback, and I appreciate your understanding. I'm open to any suggestions or alternative solutions you might have.
